Vocabulary.delete_all

vocabularies = [
  { kanji: "食べる", hiragana: "たべる", romaji: "taberu", definition: "to eat", part_of_speech: "verb" },
  { kanji: "行く", hiragana: "いく", romaji: "iku", definition: "to go", part_of_speech: "verb" },
  { kanji: "見る", hiragana: "みる", romaji: "miru", definition: "to see", part_of_speech: "verb" },
  { kanji: "話す", hiragana: "はなす", romaji: "hanasu", definition: "to speak", part_of_speech: "verb" },
  { kanji: "書く", hiragana: "かく", romaji: "kaku", definition: "to write", part_of_speech: "verb" },
  { kanji: "読む", hiragana: "よむ", romaji: "yomu", definition: "to read", part_of_speech: "verb" },
  { kanji: "聞く", hiragana: "きく", romaji: "kiku", definition: "to hear", part_of_speech: "verb" },
  { kanji: "来る", hiragana: "くる", romaji: "kuru", definition: "to come", part_of_speech: "verb" },
  { kanji: "する", hiragana: "する", romaji: "suru", definition: "to do", part_of_speech: "verb" },
  { kanji: "考える", hiragana: "かんがえる", romaji: "kangaeru", definition: "to think", part_of_speech: "verb" },
  { kanji: "人", hiragana: "ひと", romaji: "hito", definition: "person", part_of_speech: "noun" },
  { kanji: "本", hiragana: "ほん", romaji: "hon", definition: "book", part_of_speech: "noun" },
  { kanji: "家", hiragana: "いえ", romaji: "ie", definition: "house", part_of_speech: "noun" },
  { kanji: "学校", hiragana: "がっこう", romaji: "gakkō", definition: "school", part_of_speech: "noun" },
  { kanji: "会社", hiragana: "かいしゃ", romaji: "kaisha", definition: "company", part_of_speech: "noun" },
  { kanji: "食べ物", hiragana: "たべもの", romaji: "tabemono", definition: "food", part_of_speech: "noun" },
  { kanji: "水", hiragana: "みず", romaji: "mizu", definition: "water", part_of_speech: "noun" },
  { kanji: "友達", hiragana: "ともだち", romaji: "tomodachi", definition: "friend", part_of_speech: "noun" },
  { kanji: "時間", hiragana: "じかん", romaji: "jikan", definition: "time", part_of_speech: "noun" },
  { kanji: "お金", hiragana: "おかね", romaji: "okane", definition: "money", part_of_speech: "noun" },
  { kanji: "大きい", hiragana: "おおきい", romaji: "ōkii", definition: "big", part_of_speech: "adjective" },
  { kanji: "小さい", hiragana: "ちいさい", romaji: "chiisai", definition: "small", part_of_speech: "adjective" },
  { kanji: "赤い", hiragana: "あかい", romaji: "akai", definition: "red", part_of_speech: "adjective" },
  { kanji: "青い", hiragana: "あおい", romaji: "aoi", definition: "blue", part_of_speech: "adjective" },
  { kanji: "白い", hiragana: "しろい", romaji: "shiroi", definition: "white", part_of_speech: "adjective" },
  { kanji: "黒い", hiragana: "くろい", romaji: "kuroi", definition: "black", part_of_speech: "adjective" },
  { kanji: "美味しい", hiragana: "おいしい", romaji: "oishii", definition: "delicious", part_of_speech: "adjective" },
  { kanji: "楽しい", hiragana: "たのしい", romaji: "tanoshii", definition: "fun", part_of_speech: "adjective" },
  { kanji: "悲しい", hiragana: "かなしい", romaji: "kanashii", definition: "sad", part_of_speech: "adjective" },
  { kanji: "嬉しい", hiragana: "うれしい", romaji: "ureshii", definition: "happy", part_of_speech: "adjective" },
  { kanji: "とても", hiragana: "とても", romaji: "totemo", definition: "very", part_of_speech: "adverb" },
  { kanji: "少し", hiragana: "すこし", romaji: "sukoshi", definition: "a little", part_of_speech: "adverb" },
  { kanji: "早く", hiragana: "はやく", romaji: "hayaku", definition: "quickly", part_of_speech: "adverb" },
  { kanji: "ゆっくり", hiragana: "ゆっくり", romaji: "yukkuri", definition: "slowly", part_of_speech: "adverb" },
  { kanji: "よく", hiragana: "よく", romaji: "yoku", definition: "well", part_of_speech: "adverb" },
  { kanji: "悪い", hiragana: "わるい", romaji: "warui", definition: "bad", part_of_speech: "adverb" },
  { kanji: "簡単", hiragana: "かんたん", romaji: "kantan", definition: "easy", part_of_speech: "adverb" },
  { kanji: "難しい", hiragana: "むずかしい", romaji: "muzukashii", definition: "difficult", part_of_speech: "adverb" },
  { kanji: "きっと", hiragana: "きっと", romaji: "kitto", definition: "surely", part_of_speech: "adverb" },
  { kanji: "たぶん", hiragana: "たぶん", romaji: "tabun", definition: "probably", part_of_speech: "adverb" },
  { kanji: "ありがとう", hiragana: "ありがとう", romaji: "arigatō", definition: "thank you", part_of_speech: "other" },
  { kanji: "ごめんなさい", hiragana: "ごめんなさい", romaji: "gomennasai", definition: "I'm sorry", part_of_speech: "other" },
  { kanji: "はい", hiragana: "はい", romaji: "hai", definition: "yes", part_of_speech: "other" },
  { kanji: "いいえ", hiragana: "いいえ", romaji: "iie", definition: "no", part_of_speech: "other" },
  { kanji: "こんにちは", hiragana: "こんにちは", romaji: "konnichiwa", definition: "hello (afternoon)", part_of_speech: "other" },
  { kanji: "おはようございます", hiragana: "おはようございます", romaji: "ohayō gozaimasu", definition: "good morning", part_of_speech: "other" },
  { kanji: "こんばんは", hiragana: "こんばんは", romaji: "konbanwa", definition: "good evening", part_of_speech: "other" },
  { kanji: "さようなら", hiragana: "さようなら", romaji: "sayōnara", definition: "goodbye", part_of_speech: "other" },
  { kanji: "大丈夫", hiragana: "だいじょうぶ", romaji: "daijōbu", definition: "okay", part_of_speech: "other" },
  { kanji: "頑張って", hiragana: "がんばって", romaji: "ganbatte", definition: "do your best", part_of_speech: "other" },
  { kanji: "浴びる", hiragana: "あびる", romaji: "abiru", definition: "to take a bath, shower", part_of_speech: "verb" },
  { kanji: "上がる", hiragana: "あがる", romaji: "agaru", definition: "to go up", part_of_speech: "verb" },
  { kanji: "あげる", hiragana: "あげる", romaji: "ageru", definition: "to give", part_of_speech: "verb" },
  { kanji: "会う", hiragana: "あう", romaji: "au", definition: "to meet", part_of_speech: "verb" },
  { kanji: "挨拶", hiragana: "あいさつ", romaji: "aisatsu", definition: "greeting", part_of_speech: "verb" },
  { kanji: "会いたい", hiragana: "あいたい", romaji: "aitai", definition: "want to meet", part_of_speech: "verb" },
  { kanji: "開ける", hiragana: "あける", romaji: "akeru", definition: "to open", part_of_speech: "verb" },
  { kanji: "開く", hiragana: "あく", romaji: "aku", definition: "to open", part_of_speech: "verb" },
  { kanji: "洗う", hiragana: "あらう", romaji: "arau", definition: "to wash", part_of_speech: "verb" },
  { kanji: "歩く", hiragana: "あるく", romaji: "aruku", definition: "to walk", part_of_speech: "verb" },
  { kanji: "遊ぶ", hiragana: "あそぶ", romaji: "asobu", definition: "to play, hang out", part_of_speech: "verb" },
  { kanji: "出す", hiragana: "だす", romaji: "dasu", definition: "to take out", part_of_speech: "verb" },
  { kanji: "出かけます", hiragana: "でかけます", romaji: "dekake masu", definition: "to go out", part_of_speech: "verb" },
  { kanji: "出ます", hiragana: "でます", romaji: "demasu", definition: "to leave, go out", part_of_speech: "verb" },
  { kanji: "電話します", hiragana: "でんわします", romaji: "denwashimasu", definition: "to call, to phone", part_of_speech: "verb" },
  { kanji: "選ぶ", hiragana: "えらぶ", romaji: "erabimasu", definition: "to choose", part_of_speech: "verb" },
  { kanji: "吹く", hiragana: "ふく", romaji: "fuku", definition: "to blow", part_of_speech: "verb" },
  { kanji: "降る", hiragana: "ふる", romaji: "furu", definition: "to fall (rain, snow)", part_of_speech: "verb" },
  { kanji: "います", hiragana: "います", romaji: "imasu", definition: "to be (for people)", part_of_speech: "verb" },
  { kanji: "できます", hiragana: "できます", romaji: "dekimasu", definition: "to be able to, can", part_of_speech: "verb" },
  { kanji: "好き", hiragana: "すき", romaji: "suki", definition: "to like", part_of_speech: "verb" },
  { kanji: "入ります", hiragana: "はいます", romaji: "hairimasu", definition: "to enter, come to, join", part_of_speech: "verb" },
  { kanji: "履きます", hiragana: "はきます", romaji: "hakimasu", definition: "to put on, wear", part_of_speech: "verb" },
  { kanji: "話す", hiragana: "はなす", romaji: "hanasu", definition: "to talk", part_of_speech: "verb" },
  { kanji: "払う", hiragana: "はらう", romaji: "harau", definition: "to pay", part_of_speech: "verb" },
  { kanji: "走る", hiragana: "はしる", romaji: "hashiru", definition: "to run", part_of_speech: "verb" },
  { kanji: "働きます", hiragana: "はたらきます", romaji: "hatarakimasu", definition: "to work", part_of_speech: "verb" },
  { kanji: "光る", hiragana: "ひかる", romaji: "hikaru", definition: "to shine, light up", part_of_speech: "verb" },
  { kanji: "引く", hiragana: "ひく", romaji: "hiku", definition: "to play (an instrument)", part_of_speech: "verb" },
  { kanji: "引き出します", hiragana: "ひきだします", romaji: "hikidashimasu", definition: "to withdraw (money)", part_of_speech: "verb" },
  { kanji: "引きます", hiragana: "ひきます", romaji: "hikimasu", definition: "to catch (a cold)", part_of_speech: "verb" },
  { kanji: "引っ越す", hiragana: "ひっこす", romaji: "hikkosu", definition: "to move, change residence", part_of_speech: "verb" },
  { kanji: "開く", hiragana: "ひらく", romaji: "hiraku", definition: "to open", part_of_speech: "verb" },
  { kanji: "翻訳する", hiragana: "ほんやくする", romaji: "honyakusu", definition: "to translate", part_of_speech: "verb" },
  { kanji: "欲しい", hiragana: "ほしい", romaji: "hoshii", definition: "to want, desire, need", part_of_speech: "verb" },
  { kanji: "行きます", hiragana: "いきます", romaji: "ikimasu", definition: "to go (to a destination)", part_of_speech: "verb" },
  { kanji: "行きたい", hiragana: "いきたい", romaji: "ikitai", definition: "want to go", part_of_speech: "verb" },
  { kanji: "入ります", hiragana: "はいます", romaji: "hairimasu", definition: "to enter, make (an appointment), put in", part_of_speech: "verb" },
  { kanji: "入ります", hiragana: "いります", romaji: "irimasu", definition: "to need", part_of_speech: "verb" },
  { kanji: "入れる", hiragana: "いれる", romaji: "ireru", definition: "to put in, to insert", part_of_speech: "verb" },
  { kanji: "急ぐ", hiragana: "いそぐ", romaji: "isogu", definition: "to hurry", part_of_speech: "verb" },
  { kanji: "痛い", hiragana: "いたい", romaji: "itai", definition: "to hurt", part_of_speech: "adjective" },
  { kanji: "準備", hiragana: "じゅんび", romaji: "junbi", definition: "preparation", part_of_speech: "noun" },
  { kanji: "被る", hiragana: "かぶる", romaji: "kaburu", definition: "to wear (a hat)", part_of_speech: "verb" },
  { kanji: "帰ります", hiragana: "かえります", romaji: "kaerimasu", definition: "to return, come back (home)", part_of_speech: "verb" },
  { kanji: "買います", hiragana: "かいます", romaji: "kaimasu", definition: "to buy", part_of_speech: "verb" },
  { kanji: "買い物", hiragana: "かいもの", romaji: "kaimono", definition: "shopping", part_of_speech: "noun" },
  { kanji: "書く", hiragana: "かく", romaji: "kaku", definition: "to write", part_of_speech: "verb" },
  { kanji: "掛かります", hiragana: "かかります", romaji: "kakarimasu", definition: "to take (time), to cost", part_of_speech: "verb" },
  { kanji: "書く", hiragana: "かく", romaji: "kaku", definition: "to write, to draw", part_of_speech: "verb" },
  { kanji: "掛ける", hiragana: "かける", romaji: "kakeru", definition: "to call (on the phone)", part_of_speech: "verb" },
  { kanji: "借りる", hiragana: "かりる", romaji: "kariru", definition: "to borrow", part_of_speech: "verb" },
  { kanji: "片付ける", hiragana: "かたづける", romaji: "katazukeru", definition: "to tidy up", part_of_speech: "verb" },
  { kanji: "喧嘩", hiragana: "けんか", romaji: "kenka", definition: "fight", part_of_speech: "noun" },
  { kanji: "消す", hiragana: "けす", romaji: "kesu", definition: "to turn off", part_of_speech: "verb" },
  { kanji: "着替えます", hiragana: "きがえます", romaji: "kigaemasu", definition: "to change (clothes)", part_of_speech: "verb" },
  { kanji: "聞く", hiragana: "きく", romaji: "kiku", definition: "to ask", part_of_speech: "verb" },
  { kanji: "来る", hiragana: "くる", romaji: "kuru", definition: "to come", part_of_speech: "verb" },
  { kanji: "着ています", hiragana: "きています", romaji: "kiteimasu", definition: "to be wearing", part_of_speech: "verb" },
  { kanji: "筋トレします", hiragana: "きんトレします", romaji: "kintoreoshimasu", definition: "to lift weights", part_of_speech: "verb" },
  { kanji: "嫌い", hiragana: "きらい", romaji: "kirai", definition: "to hate", part_of_speech: "adjective" },
  { kanji: "混む", hiragana: "こむ", romaji: "komu", definition: "to get crowded", part_of_speech: "verb" },
  { kanji: "転びます", hiragana: "ころびます", romaji: "korobimasu", definition: "to fall", part_of_speech: "verb" },
  { kanji: "待ちます", hiragana: "まちます", romaji: "machimasu", definition: "to wait for", part_of_speech: "verb" },
  { kanji: "曲がる", hiragana: "まがる", romaji: "magaru", definition: "to turn", part_of_speech: "verb" },
  { kanji: "待つ", hiragana: "まつ", romaji: "matsu", definition: "to wait", part_of_speech: "verb" },
  { kanji: "回る", hiragana: "まわる", romaji: "mawaru", definition: "to go around", part_of_speech: "verb" },
  { kanji: "見る", hiragana: "みる", romaji: "miru", definition: "to see", part_of_speech: "verb" },
  { kanji: "見る", hiragana: "みる", romaji: "miru", definition: "to watch", part_of_speech: "verb" },
  { kanji: "見たい", hiragana: "みたい", romaji: "mitai", definition: "want to see", part_of_speech: "adjective" },
  { kanji: "見つけます", hiragana: "みつけます", romaji: "mitsukemasu", definition: "to find", part_of_speech: "verb" },
  { kanji: "持ちます", hiragana: "もちます", romaji: "mochimasu", definition: "to hold, to carry", part_of_speech: "verb" },
  { kanji: "戻る", hiragana: "もどる", romaji: "modoru", definition: "to return", part_of_speech: "verb" },
  { kanji: "もらう", hiragana: "もらう", romaji: "morau", definition: "to receive", part_of_speech: "verb" },
  { kanji: "持っています", hiragana: "もっています", romaji: "motteimasu", definition: "to have", part_of_speech: "verb" },
  { kanji: "撫でます", hiragana: "なでます", romaji: "nademasu", definition: "to pet", part_of_speech: "verb" },
  { kanji: "亡くなりました", hiragana: "なくなった", romaji: "nakunari mashta", definition: "to pass away", part_of_speech: "verb" },
  { kanji: "治ります", hiragana: "なおります", romaji: "naorimasu", definition: "to recover, to heal", part_of_speech: "verb" },
  { kanji: "並ぶ", hiragana: "ならぶ", romaji: "narabu", definition: "to line up", part_of_speech: "verb" },
  { kanji: "習う", hiragana: "ならう", romaji: "narau", definition: "to learn", part_of_speech: "verb" },
  { kanji: "なる", hiragana: "なる", romaji: "naru", definition: "to become", part_of_speech: "verb" },
  { kanji: "寝ぼけます", hiragana: "ねぼけます", romaji: "nebokemasu", definition: "to oversleep", part_of_speech: "verb" },
  { kanji: "寝ます", hiragana: "ねます", romaji: "nemasu", definition: "to sleep", part_of_speech: "verb" },
  { kanji: "似ています", hiragana: "にています", romaji: "ni nite imasu", definition: "to resemble", part_of_speech: "verb" },
  { kanji: "乗る", hiragana: "のる", romaji: "noru", definition: "to ride, to get on", part_of_speech: "verb" },
  { kanji: "脱ぐ", hiragana: "ぬぐ", romaji: "nugu", definition: "to take off (clothes)", part_of_speech: "verb" },
  { kanji: "塗ります", hiragana: "ぬります", romaji: "nurimasu", definition: "to apply (paint, cream)", part_of_speech: "verb" },
  { kanji: "起きる", hiragana: "おきます", romaji: "okimasu", definition: "to get up", part_of_speech: "verb" },
  { kanji: "起きたくない", hiragana: "おきたくない", romaji: "okitakunai", definition: "don't want to get up", part_of_speech: "adjective" },
  { kanji: "怒る", hiragana: "おこる", romaji: "okoru", definition: "to get angry", part_of_speech: "verb" },
  { kanji: "送る", hiragana: "おくる", romaji: "okuru", definition: "to send", part_of_speech: "verb" },
  { kanji: "降ります", hiragana: "おります", romaji: "orimasu", definition: "to get off", part_of_speech: "verb" },
  { kanji: "教えます", hiragana: "おしえます", romaji: "oshiemasu", definition: "to teach", part_of_speech: "verb" },
  { kanji: "押します", hiragana: "おします", romaji: "oshimasu", definition: "to press", part_of_speech: "verb" },
  { kanji: "落とします", hiragana: "おとします", romaji: "otoshimasu", definition: "to drop", part_of_speech: "verb" },
  { kanji: "泳ぎます", hiragana: "およぎます", romaji: "oyogimasu", definition: "to swim", part_of_speech: "verb" },
  { kanji: "終わる", hiragana: "おわる", romaji: "owaru", definition: "to end", part_of_speech: "verb" },
  { kanji: "料理", hiragana: "りょうり", romaji: "ryōri", definition: "cooking", part_of_speech: "noun" },
  { kanji: "探す", hiragana: "さがす", romaji: "sagasu", definition: "to look for", part_of_speech: "verb" },
  { kanji: "差します", hiragana: "さします", romaji: "sashimasu", definition: "to put up (an umbrella)", part_of_speech: "verb" },
  { kanji: "散歩します", hiragana: "さんぽします", romaji: "sanpo shimasu", definition: "to take a walk", part_of_speech: "verb" },
  { kanji: "閉まります", hiragana: "しまります", romaji: "shimarimasu", definition: "to close", part_of_speech: "verb" },
  { kanji: "閉める", hiragana: "しめる", romaji: "shimeru", definition: "to close, to shut", part_of_speech: "verb" },
  { kanji: "死ぬ", hiragana: "しぬ", romaji: "shinu", definition: "to die", part_of_speech: "verb" },
  { kanji: "調べます", hiragana: "しらべます", romaji: "shirabemasu", definition: "to investigate, to look up", part_of_speech: "verb" },
  { kanji: "紹介します", hiragana: "しょうかいします", romaji: "shōkai shimasu", definition: "to introduce", part_of_speech: "verb" },
  { kanji: "します", hiragana: "します", romaji: "shimasu", definition: "to do, to play", part_of_speech: "verb" },
  { kanji: "吸います", hiragana: "すいます", romaji: "suimasu", definition: "to smoke", part_of_speech: "verb" },
  { kanji: "したい", hiragana: "したい", romaji: "shitai", definition: "want to do", part_of_speech: "adjective" },
  { kanji: "働きます", hiragana: "はたらきます", romaji: "hatarakimasu", definition: "to work", part_of_speech: "verb" },
  { kanji: "進みます", hiragana: "すすみます", romaji: "susumimasu", definition: "to go ahead, to proceed", part_of_speech: "verb" },
  { kanji: "座る", hiragana: "すわる", romaji: "suwaru", definition: "to sit", part_of_speech: "verb" },
  { kanji: "食べます", hiragana: "たべます", romaji: "tabemasu", definition: "to eat", part_of_speech: "verb" },
  { kanji: "立つ", hiragana: "たつ", romaji: "tatsu", definition: "to stand up", part_of_speech: "verb" },
  { kanji: "立ちます", hiragana: "たちます", romaji: "tachimasu", definition: "to stand up", part_of_speech: "verb" },
  { kanji: "手伝います", hiragana: "てつだいします", romaji: "tetsudaishimasu", definition: "to help", part_of_speech: "verb" },
  { kanji: "泊まります", hiragana: "とまります", romaji: "tomarimasu", definition: "to stay (at a hotel)", part_of_speech: "verb" },
  { kanji: "撮ります", hiragana: "とります", romaji: "torimasu", definition: "to take (a photo)", part_of_speech: "verb" },
  { kanji: "通り過ぎます", hiragana: "とおりすぎます", romaji: "toorisugimasu", definition: "to pass by", part_of_speech: "verb" },
  { kanji: "使います", hiragana: "つかいます", romaji: "tsukaimasu", definition: "to use", part_of_speech: "verb" },
  { kanji: "点けます", hiragana: "つけます", romaji: "tsukemasu", definition: "to turn on (a light)", part_of_speech: "verb" },
  { kanji: "着きます", hiragana: "つきます", romaji: "tsukimasu", definition: "to arrive", part_of_speech: "verb" },
  { kanji: "釣り", hiragana: "つり", romaji: "tsuri", definition: "fishing", part_of_speech: "noun" },
  { kanji: "作ります", hiragana: "つくります", romaji: "tsukurimasu", definition: "to make", part_of_speech: "verb" },
  { kanji: "受けます", hiragana: "うけます", romaji: "ukemasu", definition: "to receive", part_of_speech: "verb" },
  { kanji: "打ちます", hiragana: "うちます", romaji: "uchimasu", definition: "to hit", part_of_speech: "verb" },
  { kanji: "運転します", hiragana: "うんてんします", romaji: "untenshimasu", definition: "to drive", part_of_speech: "verb" },
  { kanji: "別れます", hiragana: "わかれます", romaji: "wakaremasu", definition: "to break up", part_of_speech: "verb" },
  { kanji: "分かりました", hiragana: "わかりました", romaji: "wakarimashita", definition: "understood", part_of_speech: "verb" },
  { kanji: "忘れます", hiragana: "わすれます", romaji: "wasuremasu", definition: "to forget", part_of_speech: "verb" },
  { kanji: "渡ります", hiragana: "わたります", romaji: "watari masu", definition: "to cross (a road)", part_of_speech: "verb" },
  { kanji: "焼きます", hiragana: "やきます", romaji: "yakimasu", definition: "to grill, to roast", part_of_speech: "verb" },
  { kanji: "辞めます", hiragana: "やめます", romaji: "yamemasu", definition: "to quit", part_of_speech: "verb" },
  { kanji: "休みます", hiragana: "やすみます", romaji: "yasumimasu", definition: "to rest, to be absent", part_of_speech: "verb" },
  { kanji: "呼びます", hiragana: "よびます", romaji: "yobimasu", definition: "to call, to invite", part_of_speech: "verb" },
  { kanji: "読みます", hiragana: "よみます", romaji: "yomimasu", definition: "to read", part_of_speech: "verb" },
  { kanji: "読んでいます", hiragana: "よんでいます", romaji: "yondeimasu", definition: "to be reading", part_of_speech: "verb" },
  { kanji: "予約します", hiragana: "よやくします", romaji: "yoyaku suru", definition: "to reserve", part_of_speech: "verb" },
  { kanji: "家族", hiragana: "かぞく", romaji: "kazoku", definition: "family", part_of_speech: "noun" },
  { kanji: "ご両親", hiragana: "ごりょうしん", romaji: "goreoshin", definition: "your parents", part_of_speech: "noun" },
  { kanji: "両親", hiragana: "りょうしん", romaji: "ryōshin", definition: "my parents", part_of_speech: "noun" },
  { kanji: "夫", hiragana: "おっと", romaji: "otto", definition: "husband", part_of_speech: "noun" },
  { kanji: "旦那さん", hiragana: "だんなさん", romaji: "danna san", definition: "husband", part_of_speech: "noun" },
  { kanji: "ご主人", hiragana: "ごしゅじん", romaji: "goshujin", definition: "your husband", part_of_speech: "noun" },
  { kanji: "妻", hiragana: "つま", romaji: "tsuma", definition: "wife", part_of_speech: "noun" },
  { kanji: "奥さん", hiragana: "おくさん", romaji: "okusan", definition: "your wife", part_of_speech: "noun" },
  { kanji: "兄弟", hiragana: "きょうだい", romaji: "kyōdai", definition: "siblings", part_of_speech: "noun" },
  { kanji: "子供", hiragana: "こども", romaji: "okosan", definition: "children", part_of_speech: "noun" },
  { kanji: "娘", hiragana: "むすめ", romaji: "musume", definition: "daughter", part_of_speech: "noun" },
  { kanji: "息子", hiragana: "むすこ", romaji: "musuko", definition: "son", part_of_speech: "noun" },
  { kanji: "兄", hiragana: "あに", romaji: "ani", definition: "older brother", part_of_speech: "noun" },
  { kanji: "姉", hiragana: "姉", romaji: "ane", definition: "older sister", part_of_speech: "noun" },
  { kanji: "弟", hiragana: "弟", romaji: "otōto", definition: "younger brother", part_of_speech: "noun" },
  { kanji: "妹", hiragana: "いもうと", romaji: "imōto", definition: "younger sister", part_of_speech: "noun" },
  { kanji: "いとこ", hiragana: "いとこ", romaji: "いとko", definition: "cousin", part_of_speech: "noun" },
  { kanji: "姪", hiragana: "めい", romaji: "mei", definition: "niece", part_of_speech: "noun" },
  { kanji: "甥", hiragana: "おい", romaji: "oi", definition: "nephew", part_of_speech: "noun" },
  { kanji: "お父さん", hiragana: "おとうさん", romaji: "otōsan", definition: "father", part_of_speech: "noun" },
  { kanji: "祖父祖母", hiragana: "そふぼ", romaji: "sofubo", definition: "grandparents", part_of_speech: "noun" },
  { kanji: "祖父", hiragana: "そふ", romaji: "sofu", definition: "grandfather", part_of_speech: "noun" },
  { kanji: "祖母", hiragana: "そぼ", romaji: "sobo", definition: "grandmother", part_of_speech: "noun" },
  { kanji: "孫", hiragana: "まご", romaji: "mago", definition: "grandchild", part_of_speech: "noun" },
  { kanji: "孫息子", hiragana: "まごむすこ", romaji: "magomusuko", definition: "grandson", part_of_speech: "noun" },
  { kanji: "おじ", hiragana: "おじ", romaji: "oji", definition: "uncle", part_of_speech: "noun" },
  { kanji: "おば", hiragana: "おば", romaji: "oba", definition: "aunt", part_of_speech: "noun" },
  { kanji: "建物", hiragana: "たてもの", romaji: "tatemono", definition: "building", part_of_speech: "noun" },
  { kanji: "薬", hiragana: "くすり", romaji: "kusuri", definition: "medicine", part_of_speech: "noun" },
  { kanji: "警察", hiragana: "けいさつ", romaji: "keisatsu", definition: "police", part_of_speech: "noun" },
  { kanji: "危険", hiragana: "あぶない", romaji: "abenai", definition: "dangerous", part_of_speech: "adjective" },
  { kanji: "病院", hiragana: "びょういん", romaji: "byōin", definition: "hospital", part_of_speech: "noun" },
  { kanji: "救急車", hiragana: "きゅうきゅうしゃ", romaji: "kyūkyūsha", definition: "ambulance", part_of_speech: "noun" },
  { kanji: "電話番号", hiragana: "でんわばんごう", romaji: "denwabangō", definition: "phone number", part_of_speech: "noun" },
  { kanji: "夏", hiragana: "なつ", romaji: "natsu", definition: "summer", part_of_speech: "noun" },
  { kanji: "海", hiragana: "うみ", romaji: "umi", definition: "beach", part_of_speech: "noun" },
  { kanji: "晴れ", hiragana: "はれ", romaji: "hare", definition: "sunny", part_of_speech: "noun" },
  { kanji: "春", hiragana: "はる", romaji: "haru", definition: "spring", part_of_speech: "noun" },
  { kanji: "春休み", hiragana: "はるやすみ", romaji: "haru yasumi", definition: "spring break", part_of_speech: "noun" },
  { kanji: "雨", hiragana: "あめ", romaji: "ame", definition: "rain", part_of_speech: "noun" },
  { kanji: "天気", hiragana: "てんき", romaji: "tenki", definition: "weather", part_of_speech: "noun" },
  { kanji: "暖かい", hiragana: "あたたかい", romaji: "atatakai", definition: "warm", part_of_speech: "adjective" },
  { kanji: "暑い", hiragana: "あつい", romaji: "atsui", definition: "hot", part_of_speech: "adjective" },
  { kanji: "秋", hiragana: "あき", romaji: "aki", definition: "autumn", part_of_speech: "noun" },
  { kanji: "寒い", hiragana: "さむい", romaji: "samui", definition: "cold", part_of_speech: "adjective" },
  { kanji: "冬", hiragana: "ふゆ", romaji: "fuyu", definition: "winter", part_of_speech: "noun" },
  { kanji: "雪", hiragana: "ゆき", romaji: "yuki", definition: "snow", part_of_speech: "noun" },
  { kanji: "家", hiragana: "うち", romaji: "uchi", definition: "house", part_of_speech: "noun" },
  { kanji: "仕事", hiragana: "しごと", romaji: "shigoto", definition: "work", part_of_speech: "noun" },
  { kanji: "学校", hiragana: "がっこう", romaji: "gakkō", definition: "school", part_of_speech: "noun" },
  { kanji: "家事", hiragana: "かじ", romaji: "kaji", definition: "chores", part_of_speech: "noun" },
  { kanji: "宿題", hiragana: "しゅくだい", romaji: "shukudai", definition: "homework", part_of_speech: "noun" },
  { kanji: "掃除", hiragana: "そうじ", romaji: "sōji", definition: "cleaning", part_of_speech: "noun" },
  { kanji: "洗濯", hiragana: "せんたく", romaji: "sentaku", definition: "laundry", part_of_speech: "noun" },
  { kanji: "お風呂", hiragana: "おふろ", romaji: "ofuro", definition: "bath", part_of_speech: "noun" },
  { kanji: "旅行", hiragana: "りょこう", romaji: "ryokō", definition: "trip, travel", part_of_speech: "noun" },
  { kanji: "博物館", hiragana: "はくぶつかん", romaji: "hakubutsukan", definition: "museum", part_of_speech: "noun" },
  { kanji: "美術館", hiragana: "びじゅつかん", romaji: "bijutsukan", definition: "art museum", part_of_speech: "noun" },
  { kanji: "美術", hiragana: "びじゅつ", romaji: "bijutsu", definition: "art", part_of_speech: "noun" },
  { kanji: "絵", hiragana: "え", romaji: "e", definition: "painting", part_of_speech: "noun" },
  { kanji: "写真", hiragana: "しゃしん", romaji: "shashin", definition: "photo", part_of_speech: "noun" },
  { kanji: "写真家", hiragana: "しゃしんか", romaji: "shashinka", definition: "photographer", part_of_speech: "noun" },
  { kanji: "動物園", hiragana: "どうぶつえん", romaji: "dōbutsuen", definition: "zoo", part_of_speech: "noun" },
  { kanji: "広場", hiragana: "ひろば", romaji: "hiroba", definition: "plaza", part_of_speech: "noun" },
  { kanji: "飛行機", hiragana: "ひこうき", romaji: "hikoki", definition: "airplane", part_of_speech: "noun" },
  { kanji: "料理", hiragana: "りょうり", romaji: "ryōri", definition: "cooking", part_of_speech: "noun" },
  { kanji: "席", hiragana: "せき", romaji: "seki", definition: "seat", part_of_speech: "noun" },
  { kanji: "城", hiragana: "しろ", romaji: "shiro", definition: "castle", part_of_speech: "noun" },
  { kanji: "庭", hiragana: "にわ", romaji: "niwa", definition: "garden", part_of_speech: "noun" },
  { kanji: "観光", hiragana: "かんこう", romaji: "kankō", definition: "sightseeing", part_of_speech: "noun" },
  { kanji: "楽しみ", hiragana: "たのしみ", romaji: "tanoshimi", definition: "enjoyment", part_of_speech: "noun" },
  { kanji: "窓", hiragana: "まど", romaji: "mado", definition: "window", part_of_speech: "noun" },
  { kanji: "動画", hiragana: "どうが", romaji: "dōga", definition: "video", part_of_speech: "noun" },
  { kanji: "野菜", hiragana: "やさい", romaji: "yasai", definition: "vegetable", part_of_speech: "noun" },
  { kanji: "卵", hiragana: "たまご", romaji: "tamago", definition: "egg", part_of_speech: "noun" },
  { kanji: "醤油", hiragana: "しょうゆ", romaji: "shōyu", definition: "soy sauce", part_of_speech: "noun" },
  { kanji: "魚", hiragana: "さかな", romaji: "sakana", definition: "fish", part_of_speech: "noun" },
  { kanji: "塩", hiragana: "しお", romaji: "shio", definition: "salt", part_of_speech: "noun" },
  { kanji: "暇", hiragana: "ひま", romaji: "hima", definition: "free time", part_of_speech: "noun" },
  { kanji: "教室", hiragana: "きょうしつ", romaji: "kyōshitsu", definition: "classroom", part_of_speech: "noun" },
  { kanji: "授業", hiragana: "じゅぎょう", romaji: "jugyō", definition: "lesson", part_of_speech: "noun" },
  { kanji: "質問", hiragana: "しつもん", romaji: "shitsumon", definition: "question", part_of_speech: "noun" },
  { kanji: "締め切り", hiragana: "しめきり", romaji: "shimekiri", definition: "deadline", part_of_speech: "noun" },
  { kanji: "同僚", hiragana: "どうりょう", romaji: "dōryō", definition: "colleague", part_of_speech: "noun" },
  { kanji: "会社", hiragana: "かいしゃ", romaji: "kaisha", definition: "company", part_of_speech: "noun" },
  { kanji: "図書館", hiragana: "としょかん", romaji: "toshokan", definition: "library", part_of_speech: "noun" },
  { kanji: "辞書", hiragana: "じしょ", romaji: "jisho", definition: "dictionary", part_of_speech: "noun" },
  { kanji: "博物館", hiragana: "はくぶつかん", romaji: "hakubutsukan", definition: "museum", part_of_speech: "noun" },
  { kanji: "入り口", hiragana: "いりぐち", romaji: "iriguchi", definition: "entrance", part_of_speech: "noun" },
  { kanji: "選手", hiragana: "せんしゅ", romaji: "senshu", definition: "player", part_of_speech: "noun" },
  { kanji: "運動", hiragana: "うんどう", romaji: "undō", definition: "exercise", part_of_speech: "noun" },
  { kanji: "入場料", hiragana: "にゅうじょうりょう", romaji: "nyūjōryō", definition: "admission fee", part_of_speech: "noun" },
  { kanji: "大人", hiragana: "おとな", romaji: "otona", definition: "adult", part_of_speech: "noun" },
  { kanji: "練習", hiragana: "れんしゅう", romaji: "renshū", definition: "practice", part_of_speech: "noun" },
  { kanji: "勉強", hiragana: "べんきょう", romaji: "benkyō", definition: "study", part_of_speech: "noun" },
  { kanji: "誕生日", hiragana: "たんじょうび", romaji: "tanjōbi", definition: "birthday", part_of_speech: "noun" },
  { kanji: "専攻", hiragana: "せんこう", romaji: "senkō", definition: "major", part_of_speech: "noun" },
  { kanji: "質問", hiragana: "しつもん", romaji: "shitsumon", definition: "question", part_of_speech: "noun" },
  { kanji: "数学", hiragana: "すうがく", romaji: "sūgaku", definition: "math", part_of_speech: "noun" },
  { kanji: "寮", hiragana: "りょう", romaji: "ryō", definition: "dorm", part_of_speech: "noun" },
  { kanji: "景色", hiragana: "けしき", romaji: "keshiki", definition: "scenery", part_of_speech: "noun" },
  { kanji: "川", hiragana: "かわ", romaji: "kawa", definition: "river", part_of_speech: "noun" },
  { kanji: "胡椒", hiragana: "こしょう", romaji: "koshō", definition: "pepper", part_of_speech: "noun" },
  { kanji: "牛肉", hiragana: "ぎゅうにく", romaji: "gyūniku", definition: "beef", part_of_speech: "noun" },
  { kanji: "中華街", hiragana: "ちゅうかがち", romaji: "chūkagai", definition: "Chinatown", part_of_speech: "noun" },
  { kanji: "受付", hiragana: "うけつけ", romaji: "uketsuke", definition: "front desk", part_of_speech: "noun" },
  { kanji: "箸", hiragana: "はし", romaji: "hashi", definition: "chopsticks", part_of_speech: "noun" },
  { kanji: "お釣り", hiragana: "おつり", romaji: "otsuri", definition: "change", part_of_speech: "noun" },
  { kanji: "会計", hiragana: "かいけい", romaji: "kaikei", definition: "cashier", part_of_speech: "noun" },
  { kanji: "全部", hiragana: "ぜんぶ", romaji: "zenbu", definition: "all", part_of_speech: "pronoun" },
  { kanji: "店員", hiragana: "てんいん", romaji: "ten'in", definition: "shop assistant, waiter", part_of_speech: "noun" },
  { kanji: "氷", hiragana: "こおり", romaji: "kōri", definition: "ice", part_of_speech: "noun" },
  { kanji: "牛乳", hiragana: "ぎゅうにゅう", romaji: "gyūnyū", definition: "milk", part_of_speech: "noun" },
  { kanji: "俳優", hiragana: "はいゆう", romaji: "haiyū", definition: "actor", part_of_speech: "noun" },
  { kanji: "女優", hiragana: "じょうゆう", romaji: "jōyū", definition: "actress", part_of_speech: "noun" },
  { kanji: "文化", hiragana: "ぶんか", romaji: "bunka", definition: "culture", part_of_speech: "noun" },
  { kanji: "水族館", hiragana: "すいぞくかん", romaji: "suizokukan", definition: "aquarium", part_of_speech: "noun" },
  { kanji: "味", hiragana: "あじ", romaji: "aji", definition: "flavor", part_of_speech: "noun" },
  { kanji: "道", hiragana: "みち", romaji: "michi", definition: "street, road, path", part_of_speech: "noun" },
  { kanji: "通り", hiragana: "とおり", romaji: "tōri", definition: "street", part_of_speech: "noun" },
  { kanji: "レジ袋", hiragana: "れじぶくろ", romaji: "rejibakuro", definition: "plastic bag", part_of_speech: "noun" },
  { kanji: "電池", hiragana: "でんち", romaji: "denchi", definition: "battery", part_of_speech: "noun" },
  { kanji: "グッズ", hiragana: "グッズ", romaji: "guzzu", definition: "merchandise", part_of_speech: "noun" },
  { kanji: "食堂", hiragana: "しょくどう", romaji: "shokudō", definition: "cafeteria", part_of_speech: "noun" },
  { kanji: "歴史", hiragana: "れきし", romaji: "rekishi", definition: "history", part_of_speech: "noun" },
  { kanji: "田舎", hiragana: "いなか", romaji: "inaka", definition: "countryside", part_of_speech: "noun" },
  { kanji: "銀行", hiragana: "ぎんこう", romaji: "ginkō", definition: "bank", part_of_speech: "noun" },
  { kanji: "郵便局", hiragana: "ゆうびんきょく", romaji: "yūbinkyoku", definition: "post office", part_of_speech: "noun" },
  { kanji: "空気", hiragana: "くうき", romaji: "kūki", definition: "air", part_of_speech: "noun" },
  { kanji: "卒業", hiragana: "そつぎょう", romaji: "sotsugyō", definition: "graduation", part_of_speech: "noun" },
  { kanji: "靴下", hiragana: "くつした", romaji: "kutsushita", definition: "socks", part_of_speech: "noun" },
  { kanji: "マフラー", hiragana: "マフラー", romaji: "mafura", definition: "scarf", part_of_speech: "noun" },
  { kanji: "スイカ", hiragana: "すいか", romaji: "suika", definition: "watermelon", part_of_speech: "noun" },
  { kanji: "さつまいも", hiragana: "さつまいも", romaji: "satsumaimo", definition: "sweet potato", part_of_speech: "noun" },
  { kanji: "みかん", hiragana: "みかん", romaji: "mikan", definition: "mandarin orange", part_of_speech: "noun" },
  { kanji: "ダンボ", hiragana: "ダンボ", romaji: "danbo", definition: "heater", part_of_speech: "noun" },
  { kanji: "車", hiragana: "くるま", romaji: "kuruma", definition: "car", part_of_speech: "noun" },
  { kanji: "自転車", hiragana: "じてんしゃ", romaji: "jitensha", definition: "bicycle", part_of_speech: "noun" },
  { kanji: "用事", hiragana: "ようじ", romaji: "yōji", definition: "errand", part_of_speech: "noun" },
  { kanji: "椅子", hiragana: "いす", romaji: "isu", definition: "chair", part_of_speech: "noun" },
  { kanji: "小説", hiragana: "しょうせつ", romaji: "shōsetsu", definition: "novel", part_of_speech: "noun" },
  { kanji: "予定", hiragana: "よてい", romaji: "yotei", definition: "plan, schedule", part_of_speech: "noun" },
  { kanji: "遅れ", hiragana: "おくれ", romaji: "okure", definition: "lateness", part_of_speech: "noun" },
  { kanji: "たち", hiragana: "たち", romaji: "tachi", definition: "others", part_of_speech: "noun" },
  { kanji: "港", hiragana: "みなと", romaji: "minato", definition: "port", part_of_speech: "noun" },
  { kanji: "船", hiragana: "ふね", romaji: "fune", definition: "ship", part_of_speech: "noun" },
  { kanji: "水着", hiragana: "みずぎ", romaji: "mizugi", definition: "swimsuit", part_of_speech: "noun" },
  { kanji: "食べ放題", hiragana: "たべほうだい", romaji: "tabehodai", definition: "all-you-can-eat", part_of_speech: "noun" },
  { kanji: "事故", hiragana: "じこ", romaji: "jiko", definition: "accident", part_of_speech: "noun" },
  { kanji: "池", hiragana: "いけ", romaji: "ike", definition: "pond", part_of_speech: "noun" },
  { kanji: "屋台", hiragana: "やたい", romaji: "yatai", definition: "food stall", part_of_speech: "noun" },
  { kanji: "橋", hiragana: "はし", romaji: "hashi", definition: "bridge", part_of_speech: "noun" },
  { kanji: "鴨", hiragana: "かも", romaji: "kamo", definition: "duck", part_of_speech: "noun" },
  { kanji: "赤ちゃん", hiragana: "あかちゃん", romaji: "akachan", definition: "baby", part_of_speech: "noun" },
  { kanji: "鳥", hiragana: "とり", romaji: "tori", definition: "bird", part_of_speech: "noun" },
  { kanji: "足", hiragana: "あし", romaji: "ashi", definition: "leg", part_of_speech: "noun" },
  { kanji: "麒麟", hiragana: "きりん", romaji: "kirin", definition: "giraffe", part_of_speech: "noun" },
  { kanji: "隅", hiragana: "すみ", romaji: "sumi", definition: "corner", part_of_speech: "noun" },
  { kanji: "猿", hiragana: "さる", romaji: "saru", definition: "monkey", part_of_speech: "noun" },
  { kanji: "綿菓子", hiragana: "わたがし", romaji: "watagashi", definition: "cotton candy", part_of_speech: "noun" },
  { kanji: "うさぎ", hiragana: "うさぎ", romaji: "usagi", definition: "rabbit", part_of_speech: "noun" },
  { kanji: "山羊", hiragana: "やぎ", romaji: "yagi", definition: "goat", part_of_speech: "noun" },
  { kanji: "ハンドジェル", hiragana: "ハンドジェル", romaji: "handojeru", definition: "hand sanitizer", part_of_speech: "noun" },
  { kanji: "ぬいぐるみ", hiragana: "ぬいぐるみ", romaji: "nuigurumi", definition: "stuffed doll", part_of_speech: "noun" },
  { kanji: "熱", hiragana: "ねつ", romaji: "netsu", definition: "fever", part_of_speech: "noun" },
  { kanji: "風邪", hiragana: "かぜ", romaji: "kaze", definition: "common cold", part_of_speech: "noun" },
  { kanji: "嵐", hiragana: "あらし", romaji: "arashi", definition: "storm", part_of_speech: "noun" },
  { kanji: "ノート", hiragana: "ノート", romaji: "nōto", definition: "notebook", part_of_speech: "noun" },
  { kanji: "おかゆ", hiragana: "おかゆ", romaji: "okayu", definition: "rice porridge", part_of_speech: "noun" },
  { kanji: "元気", hiragana: "げんき", romaji: "genki", definition: "fine, better", part_of_speech: "adjective" },
  { kanji: "絵本", hiragana: "えほん", romaji: "ehon", definition: "picture book", part_of_speech: "noun" },
  { kanji: "人形", hiragana: "にんぎょう", romaji: "ningyō", definition: "doll", part_of_speech: "noun" },
  { kanji: "革", hiragana: "かわ", romaji: "kawa", definition: "leather", part_of_speech: "noun" },
  { kanji: "島", hiragana: "しま", romaji: "shima", definition: "island", part_of_speech: "noun" },
  { kanji: "湖", hiragana: "みずうみ", romaji: "mizūmi", definition: "lake", part_of_speech: "noun" },
  { kanji: "村", hiragana: "むら", romaji: "mura", definition: "village", part_of_speech: "noun" },
  { kanji: "伝統旅館", hiragana: "でんとうりょかん", romaji: "dentō ryokan", definition: "traditional inn", part_of_speech: "noun" },
  { kanji: "森", hiragana: "もり", romaji: "mori", definition: "forest", part_of_speech: "noun" },
  { kanji: "周り", hiragana: "まわり", romaji: "mawari", definition: "surrounding area", part_of_speech: "noun" },
  { kanji: "キノコ", hiragana: "きのこ", romaji: "kinoko", definition: "mushroom", part_of_speech: "noun" },
  { kanji: "お客様", hiragana: "おきゃくさま", romaji: "okyaku-sama", definition: "guest", part_of_speech: "noun" },
  { kanji: "指輪", hiragana: "ゆびわ", romaji: "yubiwa", definition: "ring", part_of_speech: "noun" },
  { kanji: "メガネ", hiragana: "めがね", romaji: "megane", definition: "glasses", part_of_speech: "noun" },
  { kanji: "留学", hiragana: "りゅうがく", romaji: "ryūgaku", definition: "study abroad", part_of_speech: "noun" },
  { kanji: "文学", hiragana: "ぶんがく", romaji: "bungaku", definition: "literature", part_of_speech: "noun" },
  { kanji: "年", hiragana: "ねん", romaji: "nen", definition: "year", part_of_speech: "noun" },
  { kanji: "課題", hiragana: "かだい", romaji: "kadai", definition: "assignment", part_of_speech: "noun" },
  { kanji: "生活", hiragana: "せいかつ", romaji: "seikatsu", definition: "life", part_of_speech: "noun" },
  { kanji: "外国語", hiragana: "がいこくご", romaji: "gaikoku-go", definition: "foreign language", part_of_speech: "noun" },
  { kanji: "成績", hiragana: "せいせき", romaji: "seiseki", definition: "grade", part_of_speech: "noun" },
  { kanji: "サークル", hiragana: "サークル", romaji: "sākuru", definition: "club", part_of_speech: "noun" },
  { kanji: "バイト", hiragana: "バイト", romaji: "baito", definition: "part-time job", part_of_speech: "noun" },
  { kanji: "近所のひと", hiragana: "きんじょのひと", romaji: "kinjono hito", definition: "neighbor", part_of_speech: "noun" },
  { kanji: "玉ねぎ", hiragana: "たまねぎ", romaji: "tamanegi", definition: "onion", part_of_speech: "noun" },
  { kanji: "じゃがいも", hiragana: "じゃがいも", romaji: "jagaimo", definition: "potato", part_of_speech: "noun" },
  { kanji: "砂糖", hiragana: "さとう", romaji: "satō", definition: "sugar", part_of_speech: "noun" },
  { kanji: "小麦粉", hiragana: "こむぎこ", romaji: "komugiko", definition: "flour", part_of_speech: "noun" },
  { kanji: "茶碗", hiragana: "ちゃわん", romaji: "chawan", definition: "bowl", part_of_speech: "noun" },
  { kanji: "皿", hiragana: "さら", romaji: "sara", definition: "plate", part_of_speech: "noun" },
  { kanji: "引き出し", hiragana: "ひきだし", romaji: "hikidashi", definition: "drawer", part_of_speech: "noun" },  
  { kanji: "玄関", hiragana: "げんかん", romaji: "genkan", definition: "entrance", part_of_speech: "noun" },
  { kanji: "壁", hiragana: "かべ", romaji: "kabe", definition: "wall", part_of_speech: "noun" },
  { kanji: "家具", hiragana: "かぐ", romaji: "kagu", definition: "furniture", part_of_speech: "noun" },
  { kanji: "棚", hiragana: "棚", romaji: "tana", definition: "shelf", part_of_speech: "noun" },
  { kanji: "花瓶", hiragana: "かびん", romaji: "kabin", definition: "vase", part_of_speech: "noun" },
  { kanji: "門", hiragana: "もん", romaji: "mon", definition: "gate", part_of_speech: "noun" },
  { kanji: "頭", hiragana: "あたま", romaji: "atama", definition: "head", part_of_speech: "noun" },
  { kanji: "首", hiragana: "くび", romaji: "kubi", definition: "neck", part_of_speech: "noun" },
  { kanji: "痛い", hiragana: "いたい", romaji: "itai", definition: "hurts", part_of_speech: "adjective" },
  { kanji: "傷", hiragana: "きず", romaji: "kizu", definition: "wound", part_of_speech: "noun" },
  { kanji: "薬局", hiragana: "やくきょく", romaji: "yakkyoku", definition: "pharmacy", part_of_speech: "noun" },
  { kanji: "予約", hiragana: "よやく", romaji: "yoyaku", definition: "appointment", part_of_speech: "noun" },
  { kanji: "雑誌", hiragana: "ざっし", romaji: "zasshi", definition: "magazine", part_of_speech: "noun" },
  { kanji: "広告", hiragana: "こうこく", romaji: "kōkoku", definition: "advertisement", part_of_speech: "noun" },
  { kanji: "ゴキブリ", hiragana: "ゴキブリ", romaji: "gokibiri", definition: "cockroach", part_of_speech: "noun" },
  { kanji: "果物", hiragana: "くだもの", romaji: "kudamono", definition: "fruit", part_of_speech: "noun" },
  { kanji: "幼稚園", hiragana: "ようちえん", romaji: "yōchien", definition: "kindergarten", part_of_speech: "noun" },
  { kanji: "都市", hiragana: "とし", romaji: "toshi", definition: "city", part_of_speech: "noun" },
  { kanji: "体育", hiragana: "たいいく", romaji: "taiiku", definition: "physical education", part_of_speech: "noun" },
  { kanji: "大会", hiragana: "たいかい", romaji: "taikai", definition: "competition", part_of_speech: "noun" },
  { kanji: "学校", hiragana: "がっこう", romaji: "gakkō", definition: "school", part_of_speech: "noun" },
  { kanji: "監督", hiragana: "かんとく", romaji: "kantoku", definition: "director", part_of_speech: "noun" },
  { kanji: "高校", hiragana: "こうこう", romaji: "kōkō", definition: "high school", part_of_speech: "noun" },
  { kanji: "高校生", hiragana: "こうこうせい", romaji: "kōkōsei", definition: "high school student", part_of_speech: "noun" },
  { kanji: "中学生", hiragana: "ちゅうがくせい", romaji: "chūgakusei", definition: "middle school student", part_of_speech: "noun" },
  { kanji: "郊外", hiragana: "こうがい", romaji: "kōgai", definition: "suburb", part_of_speech: "noun" },
  { kanji: "お化け屋敷", hiragana: "おばけやしき", romaji: "obakeyashiki", definition: "haunted house", part_of_speech: "noun" },
  { kanji: "列", hiragana: "れつ", romaji: "retsu", definition: "line", part_of_speech: "noun" },
  { kanji: "床", hiragana: "ゆか", romaji: "yuka", definition: "floor", part_of_speech: "noun" },
  { kanji: "演技", hiragana: "えんぎ", romaji: "engi", definition: "acting", part_of_speech: "noun" },
  { kanji: "問題", hiragana: "もんだい", romaji: "mondai", definition: "problem", part_of_speech: "noun" },
  { kanji: "映画館", hiragana: "えいがかん", romaji: "eigakan", definition: "movie theater", part_of_speech: "noun" },
  { kanji: "遊園地", hiragana: "ゆうえんち", romaji: "yūenchi", definition: "amusement park", part_of_speech: "noun" },
  { kanji: "喉", hiragana: "のど", romaji: "nodo", definition: "throat", part_of_speech: "noun" },
  { kanji: "お腹", hiragana: "おなか", romaji: "onaka", definition: "stomach", part_of_speech: "noun" },
  { kanji: "ハサミ", hiragana: "はさみ", romaji: "hasami", definition: "scissors", part_of_speech: "noun" },
  { kanji: "ニンジン", hiragana: "にんじん", romaji: "ninjin", definition: "carrot", part_of_speech: "noun" },
  { kanji: "揚げ物", hiragana: "あげもの", romaji: "agemono", definition: "fried food", part_of_speech: "noun" },
  { kanji: "日焼け止め", hiragana: "ひやけどめ", romaji: "hiyakedome", definition: "sunscreen", part_of_speech: "noun" },
  { kanji: "場所", hiragana: "ばしょ", romaji: "basho", definition: "place", part_of_speech: "noun" },
  { kanji: "かき氷", hiragana: "かきごおり", romaji: "kakigōri", definition: "shaved ice", part_of_speech: "noun" },
  { kanji: "洋食", hiragana: "ようしょく", romaji: "yōshoku", definition: "western food", part_of_speech: "noun" },
  { kanji: "おごり", hiragana: "おごり", romaji: "ogori", definition: "treat", part_of_speech: "noun" },
  { kanji: "ブドウ", hiragana: "ぶどう", romaji: "budō", definition: "grape", part_of_speech: "noun" },
  { kanji: "キュウリ", hiragana: "きゅうり", romaji: "kyūri", definition: "cucumber", part_of_speech: "noun" },
  { kanji: "半分", hiragana: "はんぶん", romaji: "hanbun", definition: "half", part_of_speech: "noun" },
  { kanji: "ファミリーレストラン", hiragana: "ファミレス", romaji: "famiresu", definition: "family restaurant", part_of_speech: "noun" },
  { kanji: "結婚式", hiragana: "けっこんしき", romaji: "kekkonshiki", definition: "wedding", part_of_speech: "noun" },
  { kanji: "会場", hiragana: "かいじょう", romaji: "kaijō", definition: "venue", part_of_speech: "noun" },
  { kanji: "色", hiragana: "いろ", romaji: "iro", definition: "color", part_of_speech: "noun" },  
  { kanji: "新婦", hiragana: "しんぷ", romaji: "shinpu", definition: "bride", part_of_speech: "noun" },
  { kanji: "新郎", hiragana: "しんろう", romaji: "shinrō", definition: "groom", part_of_speech: "noun" },
  { kanji: "親戚", hiragana: "しんせき", romaji: "shinseki", definition: "relative", part_of_speech: "noun" },
  { kanji: "歌手", hiragana: "かしゅ", romaji: "kashu", definition: "singer", part_of_speech: "noun" },
  { kanji: "居酒屋", hiragana: "いざかや", romaji: "izakaya", definition: "Japanese-style pub", part_of_speech: "noun" },
  { kanji: "屋上", hiragana: "おくじょう", romaji: "okujo", definition: "rooftop", part_of_speech: "noun" },
  { kanji: "おもちゃ", hiragana: "おもちゃ", romaji: "omocha", definition: "toy", part_of_speech: "noun" },
  { kanji: "学期", hiragana: "がっき", romaji: "gakki", definition: "semester", part_of_speech: "noun" },
  { kanji: "生物学", hiragana: "せいぶつがく", romaji: "seibutsu gaku", definition: "biology", part_of_speech: "noun" },
  { kanji: "経済学", hiragana: "けいざいがく", romaji: "keizai gaku", definition: "economics", part_of_speech: "noun" },
  { kanji: "教科書", hiragana: "きょうかしょ", romaji: "kyōkasho", definition: "textbook", part_of_speech: "noun" },
  { kanji: "留学生", hiragana: "りゅうがくせい", romaji: "ryūgaku sei", definition: "foreign student", part_of_speech: "noun" },
  { kanji: "演劇", hiragana: "えんげき", romaji: "engeki", definition: "theater", part_of_speech: "noun" },
  { kanji: "免許", hiragana: "めんきょ", romaji: "menkyo", definition: "license", part_of_speech: "noun" },
  { kanji: "卓球", hiragana: "たっきゅう", romaji: "takkyū", definition: "table tennis", part_of_speech: "noun" },
  { kanji: "店", hiragana: "みせ", romaji: "mise", definition: "store", part_of_speech: "noun" },
  { kanji: "文房具", hiragana: "ぶんぼうぐ", romaji: "bunbōgu", definition: "stationery", part_of_speech: "noun" },
  { kanji: "消しゴム", hiragana: "けしゴム", romaji: "keshigomu", definition: "eraser", part_of_speech: "noun" },
  { kanji: "色鉛筆", hiragana: "いろえんぴつ", romaji: "iro enpitsu", definition: "colored pencil", part_of_speech: "noun" },
  { kanji: "ハサミ", hiragana: "はさみ", romaji: "hasami", definition: "scissors", part_of_speech: "noun" },
  { kanji: "ホッチキス", hiragana: "ほっちきす", romaji: "hotchikisu", definition: "stapler", part_of_speech: "noun" },
  { kanji: "付箋", hiragana: "ふせん", romaji: "fusen", definition: "sticky note", part_of_speech: "noun" },
  { kanji: "半額", hiragana: "はんがく", romaji: "hangaku", definition: "half price", part_of_speech: "noun" },
  { kanji: "こちら", hiragana: "こちら", romaji: "kochira", definition: "this way", part_of_speech: "pronoun" },
  { kanji: "切手", hiragana: "きって", romaji: "kitte", definition: "stamp", part_of_speech: "noun" },
  { kanji: "お金", hiragana: "おかね", romaji: "okane", definition: "money", part_of_speech: "noun" },
  { kanji: "箸", hiragana: "はし", romaji: "hashi", definition: "chopsticks", part_of_speech: "noun" },
  { kanji: "台所", hiragana: "だいどころ", romaji: "daidokoro", definition: "kitchen", part_of_speech: "noun" },
  { kanji: "寝室", hiragana: "しんしつ", romaji: "shinshitsu", definition: "bedroom", part_of_speech: "noun" },
  { kanji: "ようこそ", hiragana: "ようこそ", romaji: "yōkoso", definition: "welcome", part_of_speech: "exclamation" },
  { kanji: "机", hiragana: "つくえ", romaji: "tsukue", definition: "desk", part_of_speech: "noun" },
  { kanji: "猫", hiragana: "ねこ", romaji: "neko", definition: "cat", part_of_speech: "noun" },
  { kanji: "犬", hiragana: "いぬ", romaji: "inu", definition: "dog", part_of_speech: "noun" },
  { kanji: "外国人", hiragana: "がいこくじん", romaji: "gaikokujin", definition: "foreigner", part_of_speech: "noun" },
  { kanji: "小学生", hiragana: "しょうがくせい", romaji: "shōgakusei", definition: "elementary school student", part_of_speech: "noun" },
  { kanji: "小学四年生", hiragana: "しょうがくよねんせい", romaji: "shōgaku yonensei", definition: "fourth grader", part_of_speech: "noun" },
  { kanji: "学生", hiragana: "がくせい", romaji: "gakusei", definition: "student", part_of_speech: "noun" },
  { kanji: "大学生", hiragana: "だいがくせい", romaji: "daigakusei", definition: "university student", part_of_speech: "noun" },
  { kanji: "歌", hiragana: "うた", romaji: "uta", definition: "song", part_of_speech: "noun" },
  { kanji: "姉妹", hiragana: "しまい", romaji: "shimai", definition: "sisters", part_of_speech: "noun" },
  { kanji: "鏡", hiragana: "かがみ", romaji: "kagami", definition: "mirror", part_of_speech: "noun" },
  { kanji: "明後日", hiragana: "あさって", romaji: "asatte", definition: "the day after tomorrow", part_of_speech: "noun" },
  { kanji: "用品", hiragana: "ようひん", romaji: "yōhin", definition: "equipment", part_of_speech: "noun" },
  { kanji: "電気", hiragana: "でんき", romaji: "denki", definition: "light", part_of_speech: "noun" },
  { kanji: "手紙", hiragana: "てがみ", romaji: "tegami", definition: "letter", part_of_speech: "noun" },
  { kanji: "音楽", hiragana: "おんがく", romaji: "ongaku", definition: "music", part_of_speech: "noun" },
  { kanji: "飛行機", hiragana: "ひこうき", romaji: "hikoki", definition: "airplane", part_of_speech: "noun" },
  { kanji: "ズボン", hiragana: "ズボン", romaji: "zubon", definition: "pants", part_of_speech: "noun" },
  { kanji: "服", hiragana: "ふく", romaji: "fuku", definition: "clothes", part_of_speech: "noun" },
  { kanji: "空", hiragana: "そら", romaji: "sora", definition: "sky", part_of_speech: "noun" },
  { kanji: "雲", hiragana: "くも", romaji: "kumo", definition: "cloud", part_of_speech: "noun" },
  { kanji: "曇っています", hiragana: "くもっています", romaji: "kumotte imasu", definition: "it's cloudy", part_of_speech: "verb phrase" },
  { kanji: "本棚", hiragana: "ほんだな", romaji: "hondana", definition: "bookshelf", part_of_speech: "noun" },
  { kanji: "新聞の広告", hiragana: "しんぶんのこうこく", romaji: "shinbun no kōkoku", definition: "newspaper ad", part_of_speech: "noun phrase" },
  { kanji: "そちら", hiragana: "そちら", romaji: "sochira", definition: "that way", part_of_speech: "pronoun" },
  { kanji: "おめでとう", hiragana: "おめでとう", romaji: "omedetō", definition: "congratulations", part_of_speech: "exclamation" },
  { kanji: "時計", hiragana: "とけい", romaji: "tokei", definition: "clock", part_of_speech: "noun" },
  { kanji: "荷物", hiragana: "にもつ", romaji: "nimotsu", definition: "luggage", part_of_speech: "noun" },
  { kanji: "男", hiragana: "おとこ", romaji: "otoko", definition: "man", part_of_speech: "noun" },
  { kanji: "男の子", hiragana: "おとこのこ", romaji: "otokonoko", definition: "boy", part_of_speech: "noun" },
  { kanji: "女", hiragana: "おんな", romaji: "onna", definition: "woman", part_of_speech: "noun" },
  { kanji: "女の子", hiragana: "おんなのこ", romaji: "onna no ko", definition: "girl", part_of_speech: "noun" },
  { kanji: "人", hiragana: "ひと", romaji: "hito", definition: "person", part_of_speech: "noun" },
  { kanji: "手袋", hiragana: "てぶくろ", romaji: "tebukuro", definition: "glove", part_of_speech: "noun" },
  { kanji: "鉱物", hiragana: "こうぶつ", romaji: "kōbutsu", definition: "mineral", part_of_speech: "noun" },
  { kanji: "駅", hiragana: "えき", romaji: "eki", definition: "station", part_of_speech: "noun" },
  { kanji: "道", hiragana: "みち", romaji: "michi", definition: "road", part_of_speech: "noun" },
  { kanji: "公園", hiragana: "こうえん", romaji: "kōen", definition: "park", part_of_speech: "noun" },
  { kanji: "お店", hiragana: "おみせ", romaji: "omise", definition: "shop", part_of_speech: "noun" },
  { kanji: "山", hiragana: "やま", romaji: "yama", definition: "mountain", part_of_speech: "noun" },
  { kanji: "川", hiragana: "かわ", romaji: "kawa", definition: "river", part_of_speech: "noun" },
  { kanji: "海", hiragana: "うみ", romaji: "umi", definition: "sea", part_of_speech: "noun" },
  { kanji: "湖", hiragana: "みずうみ", romaji: "mizūmi", definition: "lake", part_of_speech: "noun" },
  { kanji: "森", hiragana: "もり", romaji: "mori", definition: "forest", part_of_speech: "noun" },
  { kanji: "畑", hiragana: "はたけ", romaji: "hatake", definition: "field", part_of_speech: "noun" },
  { kanji: "田んぼ", hiragana: "たんぼ", romaji: "tanbo", definition: "rice paddy", part_of_speech: "noun" },
  { kanji: "砂浜", hiragana: "すなはま", romaji: "sunahana", definition: "beach", part_of_speech: "noun" },
  { kanji: "川", hiragana: "かわ", romaji: "kawa", definition: "river", part_of_speech: "noun" },
  { kanji: "橋", hiragana: "はし", romaji: "hashi", definition: "bridge", part_of_speech: "noun" },
  { kanji: "トンネル", hiragana: "トンネル", romaji: "tonneru", definition: "tunnel", part_of_speech: "noun" },
  { kanji: "道路", hiragana: "どうろ", romaji: "dōro", definition: "road", part_of_speech: "noun" },
  { kanji: "交差点", hiragana: "こうさてん", romaji: "kōsaten", definition: "intersection", part_of_speech: "noun" },
  { kanji: "信号", hiragana: "しんごう", romaji: "shingō", definition: "traffic light", part_of_speech: "noun" },
  { kanji: "駐車場", hiragana: "ちゅうしゃじょう", romaji: "chūshajō", definition: "parking lot", part_of_speech: "noun" },
  { kanji: "ガソリンスタンド", hiragana: "ガソリンスタンド", romaji: "gasorin sutando", definition: "gas station", part_of_speech: "noun" },
  { kanji: "コンビニ", hiragana: "コンビニ", romaji: "konbini", definition: "convenience store", part_of_speech: "noun" },
  { kanji: "スーパーマーケット", hiragana: "スーパーマーケット", romaji: "sūpāmāketto", definition: "supermarket", part_of_speech: "noun" },
  { kanji: "デパート", hiragana: "デパート", romaji: "depāto", definition: "department store", part_of_speech: "noun" },
  { kanji: "レストラン", hiragana: "レストラン", romaji: "resutoran", definition: "restaurant", part_of_speech: "noun" },
  { kanji: "カフェ", hiragana: "カフェ", romaji: "kafe", definition: "cafe", part_of_speech: "noun" },
  { kanji: "喫茶店", hiragana: "喫茶店", romaji: "kissa-ten", definition: "coffee shop", part_of_speech: "noun" },
  { kanji: "居酒屋", hiragana: "いざかや", romaji: "izakaya", definition: "Japanese-style pub", part_of_speech: "noun" },
  { kanji: "バー", hiragana: "バー", romaji: "bā", definition: "bar", part_of_speech: "noun" },
  { kanji: "郵便局", hiragana: "ゆうびんきょく", romaji: "yūbinkyoku", definition: "post office", part_of_speech: "noun" },
  { kanji: "銀行", hiragana: "ぎんこう", romaji: "ginkō", definition: "bank", part_of_speech: "noun" },
  { kanji: "図書館", hiragana: "としょかん", romaji: "toshokan", definition: "library", part_of_speech: "noun" },

  # Part 1: Basic Adjectives
  { kanji: "近く", hiragana: "ちかく", romaji: "chikaku", definition: "nearby", part_of_speech: "adverb" },
  { kanji: "近い", hiragana: "ちかい", romaji: "chikai", definition: "near", part_of_speech: "adjective" },
  { kanji: "遠い", hiragana: "とおい", romaji: "tooi", definition: "far", part_of_speech: "adjective" },
  { kanji: "大きい", hiragana: "おおきい", romaji: "ookii", definition: "big", part_of_speech: "adjective" },
  { kanji: "小さい", hiragana: "ちいさい", romaji: "chiisai", definition: "small", part_of_speech: "adjective" },
  { kanji: "高い", hiragana: "たかい", romaji: "takai", definition: "tall, high", part_of_speech: "adjective" },
  { kanji: "低い", hiragana: "ひくい", romaji: "hiku", definition: "low", part_of_speech: "adjective" },
  { kanji: "新しい", hiragana: "あたらしい", romaji: "atarashii", definition: "new", part_of_speech: "adjective" },
  { kanji: "古い", hiragana: "ふるい", romaji: "furui", definition: "old", part_of_speech: "adjective" },
  { kanji: "多い", hiragana: "おおいい", romaji: "ooi", definition: "many, much", part_of_speech: "adjective" },
  { kanji: "少ない", hiragana: "すくない", romaji: "sukunai", definition: "few, little", part_of_speech: "adjective" },
  { kanji: "良い", hiragana: "いい", romaji: "ii", definition: "good", part_of_speech: "adjective" },
  { kanji: "悪い", hiragana: "わるい", romaji: "warui", definition: "bad", part_of_speech: "adjective" },
  { kanji: "黒い", hiragana: "くろい", romaji: "kuroi", definition: "black", part_of_speech: "adjective" },
  { kanji: "白い", hiragana: "しろい", romaji: "shiroi", definition: "white", part_of_speech: "adjective" },
  { kanji: "赤い", hiragana: "あかい", romaji: "akai", definition: "red", part_of_speech: "adjective" },
  { kanji: "青い", hiragana: "あおい", romaji: "aoi", definition: "blue", part_of_speech: "adjective" },
  { kanji: "熱い", hiragana: "あつい", romaji: "atsui", definition: "hot", part_of_speech: "adjective" },
  { kanji: "冷たい", hiragana: "つめたい", romaji: "tsumetai", definition: "cold", part_of_speech: "adjective" },
  { kanji: "美味しい", hiragana: "おいしい", romaji: "oishii", definition: "delicious", part_of_speech: "adjective" },
  { kanji: "まずい", hiragana: "まずい", romaji: "mazui", definition: "bad-tasting", part_of_speech: "adjective" },
  { kanji: "甘い", hiragana: "あまい", romaji: "amai", definition: "sweet", part_of_speech: "adjective" },
  { kanji: "苦い", hiragana: "にがい", romaji: "nigai", definition: "bitter", part_of_speech: "adjective" },
  { kanji: "辛い", hiragana: "からい", romaji: "karai", definition: "spicy", part_of_speech: "adjective" },
  { kanji: "酸っぱい", hiragana: "すっぱい", romaji: "suppai", definition: "sour", part_of_speech: "adjective" },

  # Part 2: Emotional States
  { kanji: "嬉しい", hiragana: "うれしい", romaji: "ureshii", definition: "happy", part_of_speech: "adjective" },
  { kanji: "悲しい", hiragana: "かなしい", romaji: "kanashii", definition: "sad", part_of_speech: "adjective" },
  { kanji: "怒る", hiragana: "おこる", romaji: "okoru", definition: "angry", part_of_speech: "verb" },
  { kanji: "驚く", hiragana: "おどろく", romaji: "odoroku", definition: "surprised", part_of_speech: "verb" },
  { kanji: "寂しい", hiragana: "さびしい", romaji: "sabishii", definition: "lonely", part_of_speech: "adjective" },

  # Part 3: Personality and Qualities
  { kanji: "優しい", hiragana: "やさしい", romaji: "yasashii", definition: "kind", part_of_speech: "adjective" },
  { kanji: "親切", hiragana: "しんせつ", romaji: "shinsetsu", definition: "kind", part_of_speech: "adjective" },
  { kanji: "丁寧", hiragana: "ていねい", romaji: "teinei", definition: "polite", part_of_speech: "adjective" },
  { kanji: "賢い", hiragana: "かしこい", romaji: "kasukoi", definition: "smart", part_of_speech: "adjective" },
  { kanji: "勤勉", hiragana: "きんべん", romaji: "kinben", definition: "diligent", part_of_speech: "adjective" },
  { kanji: "悪い", hiragana: "わるい", romaji: "warui", definition: "bad", part_of_speech: "adjective" },
  { kanji: "怠け者", hiragana: "なまけもの", romaji: "namakemono", definition: "lazy", part_of_speech: "noun" },
  { kanji: "傲慢", hiragana: "ごうまん", romaji: "gohman", definition: "arrogant", part_of_speech: "adjective" },
  { kanji: "意地悪", hiragana: "いじわる", romaji: "ijiwaru", definition: "mean", part_of_speech: "adjective" },
  { kanji: "愚か", hiragana: "おろか", romaji: "oroka", definition: "foolish", part_of_speech: "adjective" },

  # Part 4: States and Conditions
  { kanji: "疲れた", hiragana: "つかれた", romaji: "tsukareta", definition: "tired", part_of_speech: "adjective" },
  { kanji: "眠い", hiragana: "ねむい", romaji: "nemui", definition: "sleepy", part_of_speech: "adjective" },
  { kanji: "痛い", hiragana: "いたい", romaji: "itai", definition: "painful", part_of_speech: "adjective" },
  { kanji: "忙しい", hiragana: "いそがしい", romaji: "isogashii", definition: "busy", part_of_speech: "adjective" },
  { kanji: "静か", hiragana: "しずか", romaji: "shizuka", definition: "quiet", part_of_speech: "adjective" },
  { kanji: "賑やか", hiragana: "にぎやか", romaji: "nigiyaka", definition: "lively", part_of_speech: "adjective" },
  { kanji: "暗い", hiragana: "くらい", romaji: "kurai", definition: "dark", part_of_speech: "adjective" },
  { kanji: "明るい", hiragana: "あかるい", romaji: "akarui", definition: "bright", part_of_speech: "adjective" },
  { kanji: "汚い", hiragana: "きたない", romaji: "kitanai", definition: "dirty", part_of_speech: "adjective" },
  { kanji: "きれい", hiragana: "きれい", romaji: "kirei", definition: "clean", part_of_speech: "adjective" },

  # Adjective or other
  { kanji: "次", hiragana: "つぎ", romaji: "tsugi", definition: "next", part_of_speech: "noun" },
  { kanji: "速い", hiragana: "はやい", romaji: "hayai", definition: "fast", part_of_speech: "adjective" },
  { kanji: "ちゃんと", hiragana: "ちゃんと", romaji: "chanto", definition: "make sure / properly", part_of_speech: "adverb" },
  { kanji: "長い", hiragana: "ながい", romaji: "nagai", definition: "long", part_of_speech: "adjective" },
  { kanji: "もうすぐ", hiragana: "もうすぐ", romaji: "mousugu", definition: "soon", part_of_speech: "adverb" },
  { kanji: "すぐに", hiragana: "すぐに", romaji: "sugu ni", definition: "immediately / right away", part_of_speech: "adverb" },
  { kanji: "危ない", hiragana: "あぶない", romaji: "abunai", definition: "dangerous", part_of_speech: "adjective" },
  { kanji: "悪い", hiragana: "わるい", romaji: "warui", definition: "bad", part_of_speech: "adjective" },
  { kanji: "色々な", hiragana: "いろいろな", romaji: "iroiro (na)", definition: "various / all sorts of", part_of_speech: "adjective" },
  { kanji: "大変", hiragana: "たいへん", romaji: "taihen", definition: "tough", part_of_speech: "adjective" },
  { kanji: "楽しい", hiragana: "たのしい", romaji: "tanosii", definition: "fun", part_of_speech: "adjective" },
  { kanji: "広い", hiragana: "ひろい", romaji: "hiroi", definition: "spacious", part_of_speech: "adjective" },
  { kanji: "便利", hiragana: "べんり", romaji: "benri", definition: "convenient", part_of_speech: "adjective" },
  { kanji: "短い", hiragana: "みじかい", romaji: "mijikai", definition: "short", part_of_speech: "adjective" },
  { kanji: "一緒に", hiragana: "いっしょに", romaji: "issho ni", definition: "together", part_of_speech: "adverb" },
  { kanji: "生", hiragana: "なま", romaji: "nama", definition: "raw", part_of_speech: "adjective" },
  { kanji: "たくさん", hiragana: "たくさん", romaji: "takusan", definition: "a lot of", part_of_speech: "adverb" },
  { kanji: "おい", hiragana: "おい", romaji: "oi", definition: "a lot", part_of_speech: "adverb" },
  { kanji: "ゆっくり", hiragana: "ゆっくり", romaji: "yukkuri", definition: "relax / slowly / at ease", part_of_speech: "adverb" },
  { kanji: "前", hiragana: "まえ", romaji: "mae", definition: "front / before / ago", part_of_speech: "noun" },
  { kanji: "無料", hiragana: "むりょう", romaji: "muryo", definition: "free", part_of_speech: "adjective" },
  { kanji: "途中で", hiragana: "途中で", romaji: "tochu de", definition: "on the way", part_of_speech: "adverb" },
  { kanji: "真ん中", hiragana: "まんなか", romaji: "mannaka", definition: "middle", part_of_speech: "noun" },
  { kanji: "まず", hiragana: "まず", romaji: "mazu", definition: "first of all / to start with", part_of_speech: "adverb" },
  { kanji: "最近", hiragana: "さいきん", romaji: "saikin", definition: "recently", part_of_speech: "adverb" },
  { kanji: "そろそろ", hiragana: "そろそろ", romaji: "sorosoro", definition: "gradually / in a bit", part_of_speech: "adverb" },
  { kanji: "けっこう", hiragana: "けっこう", romaji: "kekko", definition: "fine / pretty much / quite a bit / quite often / (thanks)", part_of_speech: "adverb" },
  { kanji: "やっと", hiragana: "やっと", romaji: "yatto", definition: "finally", part_of_speech: "adverb" },
  { kanji: "一日中", hiragana: "いちにちじゅう", romaji: "ichinichiju", definition: "all day long / a day", part_of_speech: "adverb" },
  { kanji: "全然", hiragana: "ぜんぜん", romaji: "zenzen", definition: "at all", part_of_speech: "adverb" },
  { kanji: "同じ", hiragana: "おなじ", romaji: "onaji", definition: "same", part_of_speech: "adjective" },
  { kanji: "必ず", hiragana: "かならず", romaji: "kanarazu", definition: "definitely / for sure", part_of_speech: "adverb" },
  { kanji: "まあまあ", hiragana: "まあまあ", romaji: "maamaa", definition: "alright / well / fair enough", part_of_speech: "adverb" },
  { kanji: "たまに", hiragana: "たまに", romaji: "tamani", definition: "occasionally", part_of_speech: "adverb" },
  { kanji: "しばら", hiragana: "しばら", romaji: "shibara", definition: "for a while", part_of_speech: "adverb" },
  { kanji: "ほとんど", hiragana: "ほとんど", romaji: "hotondo", definition: "almost", part_of_speech: "adverb" },
  { kanji: "だけ", hiragana: "だけ", romaji: "dake", definition: "only", part_of_speech: "particle" },
  { kanji: "きっと", hiragana: "きっと", romaji: "kitto", definition: "for sure", part_of_speech: "adverb" },
  { kanji: "たまたま", hiragana: "たまたま", romaji: "tamatama", definition: "by chance / kebetulan", part_of_speech: "adverb" },
  { kanji: "どこかで", hiragana: "どこかで", romaji: "dokoka de", definition: "somewhere", part_of_speech: "adverb" },
  { kanji: "とろとろ", hiragana: "とろとろ", romaji: "torotoro", definition: "nice and gooey.. (cheese)", part_of_speech: "adverb" },
  { kanji: "ぜひ", hiragana: "ぜひ", romaji: "zehi", definition: "definitely", part_of_speech: "adverb" },
  { kanji: "遅く", hiragana: "おそく", romaji: "osoku", definition: "late", part_of_speech: "adverb" },
  { kanji: "遠く", hiragana: "遠く", romaji: "toku", definition: "far away", part_of_speech: "adverb" },

  # about time
  { kanji: "いつ", hiragana: "いつ", romaji: "itsu", definition: "when (.. wa itsu desu ka?)", part_of_speech: "adverb" },
  { kanji: "いつからですか", hiragana: "いつからですか", romaji: "itsu kara de shi ka", definition: "since when?", part_of_speech: "phrase" },
  { kanji: "の時", hiragana: "のとき", romaji: "no toki", definition: "when ..", part_of_speech: "particle" },
  { kanji: "後", hiragana: "あと", romaji: "ato", definition: "after", part_of_speech: "noun" },
  { kanji: "分", hiragana: "ぶん", romaji: "bun", definition: "minute", part_of_speech: "noun" },
  { kanji: "十分", hiragana: "じゅうぷん", romaji: "juppun", definition: "ten minutes", part_of_speech: "noun" },
  { kanji: "今日", hiragana: "きょう", romaji: "kyo", definition: "today", part_of_speech: "noun" },
  { kanji: "今夜", hiragana: "こんや", romaji: "konya", definition: "tonight / this night", part_of_speech: "noun" },
  { kanji: "今週", hiragana: "こんしゅう", romaji: "konshu", definition: "this week", part_of_speech: "noun" },
  { kanji: "週末", hiragana: "しゅうまつ", romaji: "shumatsu", definition: "on weekend", part_of_speech: "noun" },
  { kanji: "平日", hiragana: "へいじつ", romaji: "heijitsu", definition: "weekdays", part_of_speech: "noun" },
  { kanji: "朝", hiragana: "あさ", romaji: "asa", definition: "morning", part_of_speech: "noun" },
  { kanji: "今朝", hiragana: "けさ", romaji: "kesa", definition: "this morning", part_of_speech: "noun" },
  { kanji: "今晩", hiragana: "こんばん", romaji: "konbang", definition: "this evening", part_of_speech: "noun" },
  { kanji: "昼間", hiragana: "ひるま", romaji: "hiruma", definition: "daytime", part_of_speech: "noun" },
  { kanji: "夕方", hiragana: "ゆうがた", romaji: "yuugata", definition: "evening", part_of_speech: "noun" },
  { kanji: "夜", hiragana: "よる", romaji: "yoru", definition: "night", part_of_speech: "noun" },
  { kanji: "昨夜", hiragana: "ゆうべ", romaji: "yuube", definition: "last night", part_of_speech: "noun" },
  { kanji: "今回", hiragana: "こんかい", romaji: "konkai", definition: "this time", part_of_speech: "noun" },
  { kanji: "今月", hiragana: "こんげつ", romaji: "kon getsu", definition: "this month", part_of_speech: "noun" },
  { kanji: "今年", hiragana: "ことし", romaji: "ko toshi", definition: "this year", part_of_speech: "noun" },
  { kanji: "毎日", hiragana: "まいにち", romaji: "mai nichi", definition: "everyday", part_of_speech: "adverb" },
  { kanji: "毎朝", hiragana: "まいあさ", romaji: "mai asa", definition: "every morning", part_of_speech: "adverb" },
  { kanji: "毎晩", hiragana: "まいばん", romaji: "mai ban", definition: "every night", part_of_speech: "adverb" },
  { kanji: "毎週", hiragana: "まいしゅう", romaji: "mai syu", definition: "every week", part_of_speech: "adverb" },
  { kanji: "毎月", hiragana: "まいつき", romaji: "mai tsuki", definition: "every month", part_of_speech: "adverb" },
  { kanji: "毎年", hiragana: "まいとし", romaji: "mai toshi", definition: "every year", part_of_speech: "adverb" },
  { kanji: "来週", hiragana: "らいしゅう", romaji: "rai shu", definition: "next week", part_of_speech: "noun" },
  { kanji: "再来週", hiragana: "さらいしゅう", romaji: "sa rai shu", definition: "the week after next", part_of_speech: "noun" },
  { kanji: "再来年", hiragana: "さらいねん", romaji: "sa rai nen", definition: "the year after next", part_of_speech: "noun" },
  { kanji: "一昨年", hiragana: "おととし", romaji: "ototoshi", definition: "the year before last", part_of_speech: "noun" },
  { kanji: "来月", hiragana: "らいげつ", romaji: "rai getsu", definition: "next month", part_of_speech: "noun" },
  { kanji: "明日", hiragana: "あした", romaji: "ashita", definition: "tomorrow", part_of_speech: "noun" },
  { kanji: "いつも", hiragana: "いつも", romaji: "itsumo", definition: "always", part_of_speech: "adverb" },
  { kanji: "今日", hiragana: "きょう", romaji: "today", part_of_speech: "noun" },
  { kanji: "何曜日", hiragana: "なんようび", romaji: "Nanyoubi", definition: "what day", part_of_speech: "noun" },
  { kanji: "木曜日", hiragana: "もくようび", romaji: "Mokuyōbi", definition: "Thursday", part_of_speech: "noun" },
  { kanji: "金曜日", hiragana: "きんようび", romaji: "Kin'yōbi", definition: "Friday", part_of_speech: "noun" },
  { kanji: "土曜日", hiragana: "どようび", romaji: "doyoubi", definition: "Saturday", part_of_speech: "noun" },
  { kanji: "日曜日", hiragana: "にちようび", romaji: "nichiyoubi", definition: "Sunday", part_of_speech: "noun" },
  { kanji: "月曜日", hiragana: "げつようび", romaji: "Getsuyōbi", definition: "Monday", part_of_speech: "noun" },
  { kanji: "火曜日", hiragana: "かようび", romaji: "Kayōbi", definition: "Tuesday", part_of_speech: "noun" },
  { kanji: "水曜日", hiragana: "すいようび", romaji: "Suiyōbi", definition: "Wednesday", part_of_speech: "noun" },
  { kanji: "昨日", hiragana: "きのう", romaji: "kino", definition: "yesterday", part_of_speech: "noun" },
  { kanji: "先週", hiragana: "せんしゅう", romaji: "senshu", definition: "last week", part_of_speech: "noun" },
  { kanji: "先月", hiragana: "せんげつ", romaji: "Sengetsu", definition: "last month", part_of_speech: "noun" },
  { kanji: "去年", hiragana: "きょねん", romaji: "kyonen", definition: "last year", part_of_speech: "noun" },
  { kanji: "来年", hiragana: "らいねん", romaji: "rainen", definition: "next year", part_of_speech: "noun" },

  # numeral
  { kanji: "午前", hiragana: "ごぜん", romaji: "gozen", definition: "AM", part_of_speech: "noun" },
  { kanji: "正午", hiragana: "しょうご", romaji: "reji", definition: "Twelve / midnight", part_of_speech: "noun" },
  { kanji: "匹", hiragana: "びき", romaji: "biki", definition: "off", part_of_speech: "counter for animals" },
  { kanji: "百", hiragana: "ひゃく", romaji: "hyaku", definition: "hundred", part_of_speech: "numeral" },
  { kanji: "一歳", hiragana: "いっさい", romaji: "issai", definition: "1 year old", part_of_speech: "noun" },
  # ... other age-related terms ...
  { kanji: "一", hiragana: "いち", romaji: "ikko/hitotsu/tsuitachi", definition: "first (day)", part_of_speech: "numeral" },
  { kanji: "二", hiragana: "に", romaji: "futatsu/futsuka kan/niko", definition: "two (things)", part_of_speech: "numeral" },
  # ... other numbers and counters ...
  { kanji: "四時", hiragana: "よじ", romaji: "yoji", definition: "four o'clock", part_of_speech: "noun" },
  { kanji: "六時", hiragana: "ろくじ", romaji: "rokuji", definition: "six o'clock", part_of_speech: "noun" },
  # ... other time-related terms ...
  { kanji: "一月", hiragana: "いちがつ", romaji: "ichigatsu", definition: "January", part_of_speech: "noun" },
  { kanji: "四月", hiragana: "しがつ", romaji: "shigatsu", definition: "April", part_of_speech: "noun" },
  # ... other months ...
  { kanji: "二日間", hiragana: "ふつかかん", romaji: "futsukakan", definition: "2 days", part_of_speech: "noun" },
  { kanji: "三日", hiragana: "みっか", romaji: "mikka", definition: "three days", part_of_speech: "noun" },
  { kanji: "一週間", hiragana: "いっしゅうかん", romaji: "ichi shuu kan", definition: "one week", part_of_speech: "noun" },
  { kanji: "地下", hiragana: "ちか", romaji: "chika", definition: "underground level", part_of_speech: "noun" },
  { kanji: "一階", hiragana: "いっかい", romaji: "ikkai", definition: "first floor / once", part_of_speech: "noun" },
  { kanji: "一月", hiragana: "いっかげつに", romaji: "ikkagetsuni", definition: "a month", part_of_speech: "noun" },
  # ... other floors ...
  { kanji: "出口", hiragana: "でguchi", romaji: "deguchi", definition: "exit", part_of_speech: "noun" },
  { kanji: "南口", hiragana: "みなみguchi", romaji: "minami guchi", definition: "south exit", part_of_speech: "noun" },
  # ... other directions ...
  { kanji: "XはYの南にあります", hiragana: "XはYの南にあります", romaji: "X wa Y no minami ni arimasu", definition: "X is south of Y", part_of_speech: "sentence" },
  { kanji: "北東", hiragana: "ほくとう", romaji: "hokutoo", definition: "northeast", part_of_speech: "noun" },
  { kanji: "紫", hiragana: "むらさき", romaji: "murasaki", definition: "purple", part_of_speech: "noun" },
  # ... other colors ...
  { kanji: "白い", hiragana: "しろい", romaji: "shiroi no wa", definition: "a white one", part_of_speech: "adjective" },

  # New vocabulary additions
  { kanji: "本", hiragana: "ほん", romaji: "hon", definition: "book", part_of_speech: "noun" },
  { kanji: "新聞", hiragana: "しんぶん", romaji: "shinbun", definition: "newspaper", part_of_speech: "noun" },
  { kanji: "雑誌", hiragana: "ざっし", romaji: "zasshi", definition: "magazine", part_of_speech: "noun" },
  { kanji: "漫画", hiragana: "まんが", romaji: "manga", definition: "manga", part_of_speech: "noun" },
  { kanji: "小説", hiragana: "しょうせつ", romaji: "shousetsu", definition: "novel", part_of_speech: "noun" },
  { kanji: "絵本", hiragana: "えほん", romaji: "ehon", definition: "picture book", part_of_speech: "noun" },
  { kanji: "辞書", hiragana: "じしょ", romaji: "jisho", definition: "dictionary", part_of_speech: "noun" },
  { kanji: "百科事典", hiragana: "ひゃっかじてん", romaji: "hyakka jiten", definition: "encyclopedia", part_of_speech: "noun" },
  { kanji: "手紙", hiragana: "てがみ", romaji: "tegami", definition: "letter", part_of_speech: "noun" },
  { kanji: "メール", hiragana: "メール", romaji: "mēru", definition: "email", part_of_speech: "noun" },
  { kanji: "メッセージ", hiragana: "メッセージ", romaji: "messēji", definition: "message", part_of_speech: "noun" },
  { kanji: "文書", hiragana: "ぶんしょ", romaji: "bunsho", definition: "document", part_of_speech: "noun" },
  { kanji: "レポート", hiragana: "レポート", romaji: "repōto", definition: "report", part_of_speech: "noun" },
  { kanji: "作文", hiragana: "さくぶん", romaji: "sakubun", definition: "composition", part_of_speech: "noun" },
  { kanji: "日記", hiragana: "にっき", romaji: "nikki", definition: "diary", part_of_speech: "noun" },
  { kanji: "メモ", hiragana: "メモ", romaji: "memo", definition: "memo", part_of_speech: "noun" },
  { kanji: "ノート", hiragana: "ノート", romaji: "nōto", definition: "notebook", part_of_speech: "noun" },
  { kanji: "ペン", hiragana: "ペン", romaji: "pen", definition: "pen", part_of_speech: "noun" },
  { kanji: "鉛筆", hiragana: "えんぴつ", romaji: "enpitsu", definition: "pencil", part_of_speech: "noun" },
  { kanji: "ボールペン", hiragana: "ボールペン", romaji: "bōrupen", definition: "ballpoint pen", part_of_speech: "noun" },
  { kanji: "消しゴム", hiragana: "けしゴム", romaji: "keshigomu", definition: "eraser", part_of_speech: "noun" },
  { kanji: "シャープペンシル", hiragana: "シャーペンシル", romaji: "shāpen-shiru", definition: "mechanical pencil", part_of_speech: "noun" },
  { kanji: "ノートブック", hiragana: "ノートブック", romaji: "nōtobukku", definition: "notebook (computer)", part_of_speech: "noun" },
  { kanji: "に", hiragana: "に", romaji: "ni", definition: "to / at (time) / on (date)", part_of_speech: "particle" },
  { kanji: "にわ", hiragana: "にわ", romaji: "ni wa", definition: "in/by/for the", part_of_speech: "particle" },
  { kanji: "で", hiragana: "で", romaji: "de", definition: "in / by (ride)", part_of_speech: "particle" },
  { kanji: "お", hiragana: "お", romaji: "o", definition: "of", part_of_speech: "particle" },
  { kanji: "まで", hiragana: "まで", romaji: "made", definition: "to / through / even / until", part_of_speech: "particle" },
  { kanji: "まだ", hiragana: "まだ", romaji: "mada", definition: "still / yet / too", part_of_speech: "adverb" },
  { kanji: "住んでいます", hiragana: "すんでいます", romaji: "ni sundaimasu", definition: "live in", part_of_speech: "verb" },
  { kanji: "から", hiragana: "から", romaji: "tsushin", definition: "from (origin)", part_of_speech: "particle" },
  { kanji: "どうやって家に帰りますか", hiragana: "どうやっていえにかえりますか", romaji: "doo yatte  ie ni kaeri masu ka", definition: "how are you getting home", part_of_speech: "sentence" },
  { kanji: "...はいかがですか", hiragana: "...はいかがですか", romaji: "... wa DOU desu ka", definition: "how about ... ?", part_of_speech: "sentence" },
  { kanji: "...はなんですか", hiragana: "...はなんですか", romaji: ".. wa NAN desu ka", definition: "what is .. ?", part_of_speech: "sentence" },
  { kanji: "あれは何ですか", hiragana: "あれは何ですか", romaji: "are wa NAN desu ka", definition: "what is that over there", part_of_speech: "sentence" },
  { kanji: "何時", hiragana: "なんじ", romaji: "nanjini / nanjino", definition: "what time", part_of_speech: "noun" },
  { kanji: "(名前)は誰ですか", hiragana: "(名前)はだれですか", romaji: "(name)(wa)  dare (ni)", definition: "who (is it)", part_of_speech: "sentence" },
  { kanji: "どなたですか", hiragana: "どなたですか", romaji: "donata (desu ka)  ..", definition: "who (is it)", part_of_speech: "sentence" },
  { kanji: "何", hiragana: "なに", romaji: "nani", definition: "what", part_of_speech: "pronoun" },
  { kanji: "何をしますか", hiragana: "なにをしますか", romaji: "nani o shima su ka", definition: "what do you do?", part_of_speech: "sentence" },
  { kanji: "何日", hiragana: "なんにち", romaji: "nani chi kan", definition: "how many days", part_of_speech: "noun" },
  { kanji: "何日に", hiragana: "なんにちに", romaji: "nani chi ni", definition: "on which day", part_of_speech: "particle" },
  { kanji: "何年生", hiragana: "なんねんせい", romaji: "nan nen sei", definition: "what school year / what grade are you", part_of_speech: "noun" },
  { kanji: "といます", hiragana: "といます", romaji: "toimas", definition: "my name is", part_of_speech: "verb" },
  { kanji: "お願いします", hiragana: "お願いします", romaji: "onegaisimas", definition: "I need a ... please", part_of_speech: "sentence" },
  { kanji: "大丈夫", hiragana: "だいじょうぶ", romaji: "daijobu", definition: "OK", part_of_speech: "adjective" },
  { kanji: "いらっしゃいませ", hiragana: "いらっしゃいませ", romaji: "irasshaimase", definition: "welcome", part_of_speech: "sentence" },
  { kanji: "具合が悪い", hiragana: "ぐわいがわるい", romaji: "guwaigawarui", definition: "feeling sick", part_of_speech: "adjective" },
  { kanji: "出身はどこですか", hiragana: "しゅっしんはどこですか", romaji: "soushin wa DOKO desu ka", definition: "where are you from", part_of_speech: "sentence" },
  { kanji: "どこに住んでいますか", hiragana: "どこに住んでいますか", romaji: "DOKO ni sundaimasu ka", definition: "where do you live", part_of_speech: "sentence" },
  { kanji: "どんな", hiragana: "どんな", romaji: "donna  ..", definition: "what kind of..", part_of_speech: "adjective" },
  { kanji: "...はどんなところですか", hiragana: "...はどんなところですか", romaji: ".. wa DONNA (tokoro) dese ka", definition: "what kind of (place( ...", part_of_speech: "sentence" },
  { kanji: "ちょっと", hiragana: "ちょっと", romaji: "chotto", definition: "kind of", part_of_speech: "adverb" },
  { kanji: "何歳ですか / おいくつですか", hiragana: "なんさいですか / おいくつですか", romaji: "nan sai desu ka / o ikutsu desi ka", definition: "how old", part_of_speech: "sentence" },
  { kanji: "ちゃんと", hiragana: "ちゃんと", romaji: "chanto", definition: "will make sure", part_of_speech: "adverb" },
  { kanji: "そして", hiragana: "そして", romaji: "Soshite", definition: "then / and", part_of_speech: "conjunction" },
  { kanji: "行きましょう", hiragana: "いきましょう", romaji: "Ikimashou", definition: "we shall go", part_of_speech: "verb" },
  { kanji: "でも", hiragana: "でも", romaji: "demo", definition: "but", part_of_speech: "conjunction" },
  { kanji: "もっと", hiragana: "もっと", romaji: "motto", definition: "more", part_of_speech: "adverb" },
  { kanji: "一人で", hiragana: "ひとりで", romaji: "hitori de", definition: "by my self", part_of_speech: "particle" },
  { kanji: "何名様ですか", hiragana: "なんめいさまですか", romaji: "nanmei sama desuka", definition: "how many people", part_of_speech: "sentence" },
  { kanji: "何人ですか", hiragana: "なんにんですか", romaji: "nanin desu ka", definition: "how many people", part_of_speech: "sentence" },
  { kanji: "久しぶり", hiragana: "ひさしぶり", romaji: "hisashiburi", definition: "long time no see", part_of_speech: "adjective" },
  { kanji: "今から", hiragana: "いまから", romaji: "ima kara", definition: "from now / just now", part_of_speech: "particle" },
  { kanji: "どこにいるか", hiragana: "どこにいるか", romaji: "doko ni imasu ka", definition: "where are you", part_of_speech: "sentence" },
  { kanji: "みんな", hiragana: "みんな", romaji: "minna", definition: "everyone", part_of_speech: "pronoun" },
  { kanji: "したくないです", hiragana: "したくないです", romaji: "Shitakunaidesu", definition: "I don't want to do ...", part_of_speech: "sentence" }
]

unique_kanji_hiragana = Set.new

unique_vocabularies = vocabularies.select do |vocab|
  unless unique_kanji_hiragana.include?([vocab[:kanji], vocab[:hiragana]])
    unique_kanji_hiragana << [vocab[:kanji], vocab[:hiragana]]
    true
  end
end

Vocabulary.create(unique_vocabularies)
